### ISSUE TITLE
Add Edge Update and WebView2 Runtime

### ISSUE THREAD

**Issue by T0m0rr0w** [ShadowWhisperer/Remove-Edge-Chromium#3] opened 2022-06-28 16:33 UTC
Hi. Would it be possible to add these two components to the script?
Also while the script worked there is still a 48KB entry of Edge itself under Installer Programs for some reason.
Would be great if the script got rid of all 3 entries.

**Comment by ShadowWhisperer** [comment] 2022-06-28 18:54
Duplicate of [4](https://github.com/ShadowWhisperer/Remove-Edge-Chromium/issues/4)

**Closed by ShadowWhisperer** 2022-06-28 18:54 UTC
